# Dockerfile para tu modelo (basado en imagen oficial GODML)
FROM dagmalia/godml:0.4.10 AS godml-deploy

# Copia tus artefactos de modelo
WORKDIR /app
COPY models ./models
COPY godml.yml .
COPY deploy_service ./deploy_service

# Configura variables por entorno
ENV MODE=api \
    GODML_ENV=dev \
    HOST=0.0.0.0 \
    PORT=8000

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["python", "-m", "uvicorn", "godml.deploy_service.server:app", "--host", "0.0.0.0", "--port", "8000"]
